### PR TITLE
Support Ubuntu 20.04

### PR DESCRIPTION
**Pull request by krlmlr**
with SQL Server 2019.

Also changes testing to allow testing in branches and pull requests.

### CODE REVIEW

**Comment by ankane** [comment]
Hey @krlmlr, thanks for the PR! I'd like to wait until a 20.04 repository is available.

**Comment by krlmlr** [comment]
These are the official instructions to install on 20.04 -- sure we may need to change at some point.

https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15

**Comment by krlmlr** [comment]
I'm mistaken -- it works well enough on 20.04 (tests pass for dm), agree to wait until it's officially supported.

**Comment by krlmlr** [comment]
Per https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver15:

> Ubuntu 20.04 is supported starting with SQL Server 2019 CU10.

**Comment by ankane** [comment]
Awesome! Can you back out the changes to `index.js`?

**Comment by ankane** [comment]
Hey @krlmlr, added in 78806f839a7fcac573573d327d0c781b362accbb. Thanks for driving this!

**Pull request closed without merging**
